mode: rule
mixed-port: 7897
socks-port: 7898
port: 7899
log-level: info
unified-delay: true
dns:
  # 匹配到直连走system
  # 匹配到代理(不请求DNS)走代理
  # 未知域名匹配到GEOIP才会使用nameserver
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - system
  nameserver:
    - tls://dns.google#手动选择兜底国家
  direct-nameserver:
    - system
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  use-system-hosts: false
profile:
  store-selected: true

proxies:
- name: 自购香港 |链式
  type: ss
  server: 11111
  port: 11111
  udp: true
  cipher: 1111
  password: 11111
  dialer-proxy: "链式中间节点"
- name: "Claude美国家宽 |链式"
  type: socks5
  server: 1111
  port: 1111
  udp: true
  username: 1111
  password: 11111
  dialer-proxy: "链式中间节点"

# 备用机场
proxy-providers:
  # 樱花猫机场-链式代理
  Sakuracat-Chain:
    type: http
    url: "1111111111111111111111111"
    path: ./proxy_providers/Sakuracat-Chain.yaml
    interval: 3600
    proxy: 手动选择兜底国家
    size-limit: 0
    header:
      User-Agent:
      - "clash-verge/v2.2.3"
    # 没用
    health-check:
      enable: false
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 3000
      lazy: true
      expected-status: 204
    override:
      tfo: false
      mptcp: false
      udp: true
      udp-over-tcp: false
      down: "50 Mbps"
      up: "10 Mbps"
      skip-cert-verify: false
      dialer-proxy: "链式中间节点"
      ip-version: ipv4-prefer
      additional-prefix: "樱花猫| "
      additional-suffix: " |链式"
  # Linux猫猫机场-链式代理
  LinuxCat-Chain:
    type: http
    url: "111111111111111111111111111"
    path: ./proxy_providers/LinuxCat-Chain.yaml
    interval: 3600
    proxy: 手动选择兜底国家
    size-limit: 0
    header:
      User-Agent:
      - "clash-verge/v2.2.3"
    # 没用
    health-check:
      enable: false
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 3000
      lazy: true
      expected-status: 204
    override:
      tfo: false
      mptcp: false
      udp: true
      udp-over-tcp: false
      down: "50 Mbps"
      up: "10 Mbps"
      skip-cert-verify: false
      dialer-proxy: "链式中间节点"
      ip-version: ipv4-prefer
      additional-prefix: "Linux猫猫| "
      additional-suffix: " |链式"
  # 樱花猫机场-无链式代理
  Sakuracat:
    type: http
    url: "11111111111"
    path: ./proxy_providers/Sakuracat.yaml
    interval: 3600
    proxy: 手动选择兜底国家
    size-limit: 0
    header:
      User-Agent:
      - "clash-verge/v2.2.3"
    health-check:
      enable: false
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 3000
      lazy: true
      expected-status: 204
    override:
      tfo: false
      mptcp: false
      udp: true
      udp-over-tcp: false
      down: "50 Mbps"
      up: "10 Mbps"
      skip-cert-verify: false
      ip-version: ipv4-prefer
      additional-prefix: "樱花猫| "
      additional-suffix: " |无链"
      
proxy-groups:
  # 通用主控组
  - name: "手动选择兜底国家"
    type: select
    proxies:
      - "链式代理-通用"
      - "港台日新韩-节点组"
      - "香港-节点组"
      - "台湾-节点组"
      - "日本-节点组"
      - "新加坡-节点组"
      - "韩国-节点组"
      - "美国-节点组"
      - "全部节点"
  # 链式代理-中间节点组
  - name: "链式中间节点"
    type: select
    proxies:
      - "港台日新韩-节点组"
      - "香港-节点组"
      - "台湾-节点组"
      - "日本-节点组"
      - "新加坡-节点组"
      - "韩国-节点组"
      - "美国-节点组"
  # 链式终节点-通用
  - name: "链式代理-通用"
    type: select
    include-all: true
    filter: ".*链式$"
    # 规则分流组
  - name: "GPT-节点组"
    type: select
    include-all: true
    filter: ".*链式$"
  - name: "Claude-节点组"
    type: select
    include-all: true
    filter: ".*链式$"
  - name: "Telegram-节点组"
    type: select
    include-all: true
    filter: ".*链式$"
  # 全部节点(用来看的，几乎不用)
  - name: "全部节点"
    type: select
    include-all: true
  # 大陆外地区、国家组
  - name: "港台日新韩-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 180
    tolerance: 50
    timeout: 1000
    filter: ^(?!.*游戏)(?!.*25x)(?=.*(香港|台湾|新加坡|日本|韩国)).*\|无链$
  - name: "香港-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 30
    timeout: 800
    filter: ^(?!.*游戏)(?=.*香港).*?\|无链$
  - name: "台湾-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 180
    tolerance: 40
    timeout: 1000
    filter: ^(?!.*游戏)(?=.*台湾).*?\|无链$
  - name: "日本-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 240
    tolerance: 50
    timeout: 1200
    filter: ^(?!.*游戏)(?!.*25x)(?=.*日本).*?\|无链$
  - name: "新加坡-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 240
    tolerance: 50
    timeout: 1200
    filter: ^(?!.*游戏)(?=.*新加坡).*?\|无链$
  - name: "韩国-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 240
    tolerance: 50
    timeout: 1300
    filter: ^(?!.*游戏)(?=.*韩国).*?\|无链$
  - name: "美国-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 80
    timeout: 1800
    filter: ^(?!.*游戏)(?=.*美国).*?\|无链$
  # 兜底Match组
  - name: "兜底组"
    type: select
    proxies:
      - DIRECT
      - "手动选择兜底国家"
rule-providers:
  Claude:
    type: http
    path: ./rules/Claude.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.yaml"
    interval: 86400
    proxy: 手动选择兜底国家
    behavior: classical
    format: yaml

rules:
  # 特殊自定义域名
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,手动选择兜底国家
  - DOMAIN-SUFFIX,googleapis.cn,手动选择兜底国家
  - PROCESS-NAME,com.microsoft.outlooklite,手动选择兜底国家
  - DOMAIN-SUFFIX,9563067.xyz,DIRECT
  - DOMAIN-KEYWORD,epic,DIRECT
  - DOMAIN-REGEX,^dl.*mypikpak\.com$,DIRECT
  - DOMAIN,zeze.teracloud.jp,DIRECT
  # 规则集
  - GEOSITE,category-games@CN,DIRECT
  - GEOSITE,openai,GPT-节点组
  - GEOSITE,telegram,Telegram-节点组
  - RULE-SET,Claude,Claude-节点组
  # 进程匹配(Windows)
  - PROCESS-NAME,Telegram.exe,Telegram-节点组
  - PROCESS-NAME,steam.exe,手动选择兜底国家
  - PROCESS-NAME,claude.exe,Claude-节点组
  # 进程匹配(Android)
  - PROCESS-NAME,com.valvesoftware.android.steam.community,手动选择兜底国家
  - PROCESS-NAME,com.github.android,手动选择兜底国家
  - PROCESS-NAME,com.openai.chatgpt,GPT-节点组
  - PROCESS-NAME,com.anthropic.claude,Claude-节点组
    # 谷歌商店包名
  - PROCESS-NAME,com.android.vending,手动选择兜底国家
  - PROCESS-NAME,org.telegram.messenger,Telegram-节点组
  - PROCESS-NAME,com.twitter.android,手动选择兜底国家
  # 区域规则
  - GEOSITE,geolocation-!cn,手动选择兜底国家
  - GEOSITE,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  # 兜底(默认直连)
  - PROCESS-NAME,firefox.exe,手动选择兜底国家
  - MATCH,兜底组
