mode: rule
log-level: info
unified-delay: true
dns:
  # 匹配到直连走system
  # 匹配到代理(不请求DNS)走代理
  # 未知域名匹配到GEOIP才会使用nameserver
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - system
  nameserver:
    - tls://dns.google#手动选择兜底国家
  direct-nameserver:
    - system
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  use-system-hosts: false
profile:
  store-selected: true

# 自己加自己的proxies，不会弄的别管了
# proxies:


proxy-providers:
  # 樱花猫机场-链式代理
  Sakuracat-Chain:
    type: http
    url: "这里填入机场订阅链接"
    path: ./proxy_providers/Sakuracat.yaml
    interval: 3600
    proxy: 手动选择兜底国家
    size-limit: 0
    header:
      User-Agent:
      - "clash-verge/v2.2.3"
    # 没用
    health-check:
      enable: false
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 3000
      lazy: true
      expected-status: 204
    override:
      tfo: false
      mptcp: false
      udp: true
      udp-over-tcp: false
      down: "50 Mbps"
      up: "10 Mbps"
      skip-cert-verify: false
      dialer-proxy: "链式中间节点"
      ip-version: ipv4-prefer
      additional-prefix: "链式|"
      additional-suffix: "|樱花猫"
  # 樱花猫机场-无链式代理
  Sakuracat:
    type: http
    url: "这里填入机场订阅链接"
    path: ./proxy_providers/Sakuracat.yaml
    interval: 3600
    proxy: 手动选择兜底国家
    size-limit: 0
    header:
      User-Agent:
      - "clash-verge/v2.2.3"
    health-check:
      enable: false
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 3000
      lazy: true
      expected-status: 204
    override:
      tfo: false
      mptcp: false
      udp: true
      udp-over-tcp: false
      down: "50 Mbps"
      up: "10 Mbps"
      skip-cert-verify: false
      ip-version: ipv4-prefer
      additional-prefix: "无链|"
      additional-suffix: "|樱花猫"

proxy-groups:
  # 全局主控组
  - name: "手动选择兜底国家"
    type: select
    proxies:
      - "链式代理-通用"
      - "港台日新韩-节点组"
      - "香港-节点组"
      - "台湾-节点组"
      - "日本-节点组"
      - "新加坡-节点组"
      - "韩国-节点组"
      - "美国-节点组"
      - "全部节点"
  # 链式代理-中间节点组
  - name: "链式中间节点"
    type: select
    proxies:
      - "港台日新韩-节点组"
      - "香港-节点组"
      - "台湾-节点组"
      - "日本-节点组"
      - "新加坡-节点组"
      - "韩国-节点组"
      - "美国-节点组"
  # 链式代理-终节点组
  - name: "链式代理-通用"
    type: select
    include-all: true
    filter: "^链式.*"
  - name: "链式代理-美国"
    type: select
    include-all: true
    filter: "^链式.*"
  # 全部节点(用来看的，几乎不用)
  - name: "全部节点"
    type: select
    include-all: true
  # 规则分流组
  - name: "GPT-节点组"
    type: select
    proxies:
      - "链式代理-美国"
    url: "https://chatgpt.com/generate_204"
  - name: "Claude-节点组"
    type: select
    proxies:
      - "链式代理-美国"
    url: "https://claude.ai/generate_204"
  # 境外地区、国家组
  - name: "港台日新韩-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 180
    tolerance: 50
    timeout: 1000
    filter: ^(?=无链\|)(?!.*游戏)(?!.*25x).*(香港|台湾|新加坡|日本|韩国)
  - name: "香港-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 30
    timeout: 800
    filter: ^(?=无链\|)(?!.*游戏).*香港
  - name: "台湾-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 180
    tolerance: 40
    timeout: 1000
    filter: ^(?=无链\|)(?!.*游戏).*台湾
  - name: "日本-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 240
    tolerance: 50
    timeout: 1200
    filter: ^(?=无链\|)(?!.*游戏)(?!.*25x).*日本
  - name: "新加坡-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 240
    tolerance: 50
    timeout: 1200
    filter: ^(?=无链\|)(?!.*游戏).*新加坡
  - name: "韩国-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 240
    tolerance: 50
    timeout: 1300
    filter: ^(?=无链\|)(?!.*游戏).*韩国
  - name: "美国-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 80
    timeout: 1800
    filter: ^(?=无链\|)(?!.*游戏).*美国

rule-providers:
  Claude:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.yaml"
    path: ./rules/Claude.yaml
    interval: 86400

rules:
  # 特殊自定义域名
  - DOMAIN,cvb.9563067.xyz,手动选择兜底国家
  - DOMAIN,cvw.9563067.xyz,手动选择兜底国家
  - DOMAIN-SUFFIX,9563067.xyz,DIRECT
  - DOMAIN-KEYWORD,epic,DIRECT
  - DOMAIN-REGEX,^dl.*mypikpak\.com$,DIRECT
  - DOMAIN,zeze.teracloud.jp,DIRECT
  # 规则集
  - GEOSITE,category-games@CN,DIRECT
  - GEOSITE,openai,GPT-节点组
  - RULE-SET,Claude,Claude-节点组
  # 区域规则
  - GEOSITE,geolocation-!cn,手动选择兜底国家
  - GEOSITE,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  # 进程匹配(Windows)
  - PROCESS-NAME,firefox.exe,手动选择兜底国家
  - PROCESS-NAME,Telegram.exe,手动选择兜底国家
  # 进程匹配(Android)
  - PROCESS-NAME,com.android.vending,手动选择兜底国家
  - PROCESS-NAME,org.telegram.messenger,手动选择兜底国家
  - PROCESS-NAME,com.twitter.android,手动选择兜底国家
  # 默认兜底(直连)
  - MATCH,DIRECT
