# 备注：此配置IPV6完全禁止
mode: rule
mixed-port: 7897
socks-port: 7898
port: 7899
allow-lan: true
bind-address: 0.0.0.0
log-level: info
unified-delay: true
ipv6: false
# 试用
#tcp-concurrent: true
#find-process-mode: strict
dns:
  # 匹配到直连走system，因为有些DNS服务器只在内网中
  # 匹配到代理走DOH
  # 未知域名匹配到GEOIP才会使用nameserver
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - system
    - 223.6.6.6
  nameserver:
    - 这里写可信任的doh
  direct-nameserver:
    - system
  proxy-server-nameserver:
    - 这里写可信任的doh
  use-system-hosts: true
profile:
  store-selected: true

proxies:
- {name: "example", type: ss, server: example.com, port: 11111, cipher: aes-128-gcm, password: "dwadafefesfedaeda=", udp: false, dialer-proxy: "链式中间节点"}
proxy-providers:
  example-Chain:
    type: http
    url: "机场订阅"
    path: ./proxy_providers/example-Chain.yaml
    interval: 3600
    # proxy: 1自购香港 |无链
    size-limit: 0
    header:
      User-Agent:
      - "clash-verge/v2.2.3"
    # 貌似没用
    health-check:
      enable: false
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 3000
      lazy: true
      expected-status: 204
    override:
      tfo: false
      mptcp: false
      udp: true
      udp-over-tcp: false
      skip-cert-verify: false
      dialer-proxy: "链式中间节点"
      ip-version: ipv4-prefer
      additional-prefix: "example| "
      additional-suffix: " |链式"
proxy-groups:
  # 通用主控组
  - name: "手动选择兜底国家"
    type: select
    proxies: ["中转-节点组", "链式代理-通用", "港台日新韩-节点组", "香港-节点组", "台湾-节点组", "日本-节点组", "新加坡-节点组", "韩国-节点组", "美国-节点组", "全部节点"]
  # 链式代理-中间节点组
  - name: "链式中间节点"
    type: select
    proxies: ["中转-节点组", "港台日新韩-节点组", "香港-节点组", "台湾-节点组", "日本-节点组", "新加坡-节点组", "韩国-节点组", "美国-节点组"]
  # 链式终节点-通用
  - name: "链式代理-通用"
    type: select
    include-all: true
    filter: ".*链式$"
  # 中转-节点组
  - name: "中转-节点组"
    type: select
    include-all: true
    filter: ".*中转.*"
  # 规则分流组
  - name: "GPT-节点组"
    type: select
    include-all: true
    filter: ".*链式$"
    proxies: ["手动选择兜底国家", "美国-节点组"]
  - name: "Gemini-节点组"
    type: select
    include-all: true
    filter: ".*链式$"
    proxies: ["手动选择兜底国家", "链式代理-通用"]
  - name: "Claude-节点组"
    type: select
    include-all: true
    filter: ".*链式$"
    proxies: ["手动选择兜底国家", "美国-节点组"]
  - name: "Telegram-节点组"
    type: select
    include-all: true
    filter: ".*链式$"
    proxies: ["手动选择兜底国家", "链式代理-通用"]
  - name: "Spotify-节点组"
    type: select
    include-all: true
    filter: ".*链式$"
  # 全部节点(用来看的，几乎不用)
  - name: "全部节点"
    type: select
    include-all: true
  - name: "各机场流量剩余展示"
    type: select
    include-all: true
    filter: '.*流量[^0-9]*([0-9]+(\.[0-9]+)?)\s*[Gg][Bb]'
  # 国家组
  - name: "美国-节点组"
    type: select
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    timeout: 1800
    filter: ^(?!.*游戏)(?=.*(美国|US)).*?
  - name: "港台日新韩-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 60
    tolerance: 50
    timeout: 1000
    filter: ^(?!.*游戏)(?!.*25x)(?=.*(香港|HK|台湾|TW|新加坡|SG|日本|JP|韩国|KR)).*\|无链$
  - name: "香港-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 60
    tolerance: 50
    timeout: 800
    filter: ^(?!.*游戏)(?=.*(香港|HK)).*?\|无链$
  - name: "台湾-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 60
    tolerance: 50
    timeout: 1000
    filter: ^(?!.*游戏)(?=.*(台湾|TW)).*?\|无链$
  - name: "日本-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 60
    tolerance: 50
    timeout: 1200
    filter: ^(?!.*游戏)(?!.*25x)(?=.*(日本|JP)).*?\|无链$
  - name: "新加坡-节点组"
    type: fallback
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 60
    tolerance: 50
    timeout: 1200
    filter: ^(?!.*游戏)(?=.*(新加坡|SG)).*?\|无链$
  - name: "韩国-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 60
    tolerance: 50
    timeout: 1300
    filter: ^(?!.*游戏)(?=.*(韩国|KR)).*?\|无链$
  # 兜底Match组
  - name: "兜底组"
    type: select
    proxies: [DIRECT, "手动选择兜底国家"]
rule-providers:
  Claude:
    type: http
    path: ./rules/Claude.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.yaml"
    interval: 86400
    proxy: 手动选择兜底国家
    behavior: classical
    format: yaml

rules:
  # 特殊自定义域名
  - DOMAIN-SUFFIX,gog.com,DIRECT
  - DOMAIN-SUFFIX,epicgames.com,DIRECT
  - DOMAIN-KEYWORD,bing,DIRECT
  - DOMAIN-KEYWORD,sohu,DIRECT
  - DOMAIN-REGEX,^dl.*mypikpak\.com$,DIRECT
  - DOMAIN-SUFFIX,googleapis.cn,手动选择兜底国家 # 在中国备案过的谷歌域名，下面geolocation-!cn中并没有它，走直连会导致Play下载不正常
  - DOMAIN,zeze.teracloud.jp,DIRECT
  - DOMAIN-SUFFIX,shanyu520.com,DIRECT
  - DOMAIN-SUFFIX,devsleep.com,DIRECT
  - DOMAIN-SUFFIX,uiauto.dev,DIRECT
  # 规则集
  - GEOSITE,category-games@CN,DIRECT
  - GEOSITE,openai,GPT-节点组
  - GEOSITE,google-gemini,Gemini-节点组
  - GEOSITE,telegram,Telegram-节点组
  - GEOSITE,spotify,Spotify-节点组
  - RULE-SET,Claude,Claude-节点组
  # 进程匹配(Windows)
  - PROCESS-NAME,Telegram.exe,Telegram-节点组  # Telegram 桌面客户端
  - PROCESS-NAME,steam.exe,手动选择兜底国家  # Steam 游戏平台
  - PROCESS-NAME,claude.exe,Claude-节点组  # Claude AI客户端
  - PROCESS-NAME,VALORANT.exe,全部节点  # 瓦洛兰特游戏主程序
  - PROCESS-NAME,VALORANT-Win64-Shipping.exe,全部节点  # 瓦洛兰特游戏运行时
  - PROCESS-NAME,RiotClientServices.exe,全部节点  # 拳头游戏客户端服务
  - PROCESS-NAME,AimLab.exe,全部节点  # AimLab练枪软件主程序
  - PROCESS-NAME,AimLabExe.exe,全部节点  # AimLab练枪软件执行文件
  # 进程匹配(Android)
  - PROCESS-NAME,mark.via,手动选择兜底国家  # VIA浏览器
  - PROCESS-NAME,mark.via.gp,手动选择兜底国家  # VIA浏览器
  - PROCESS-NAME,com.spotify.music,Spotify-节点组  # Spotify
  - PROCESS-NAME,com.microsoft.outlooklite,手动选择兜底国家  # Outlook Lite
  - PROCESS-NAME,com.valvesoftware.android.steam.community,手动选择兜底国家  # Steam移动版
  - PROCESS-NAME,com.github.android,手动选择兜底国家  # GitHub移动版
  - PROCESS-NAME,com.openai.chatgpt,GPT-节点组  # ChatGPT官方应用
  - PROCESS-NAME,com.anthropic.claude,Claude-节点组  # Claude AI官方应用
  - PROCESS-NAME,org.telegram.messenger,Telegram-节点组  # Telegram官方
  - PROCESS-NAME,org.thunderdog.challegram,Telegram-节点组  # Telegram X
  - PROCESS-NAME,com.twitter.android,手动选择兜底国家  # Twitter/X
  - PROCESS-NAME,com.android.vending,手动选择兜底国家  # Google Play商店
  # 国家规则
  - GEOSITE,geolocation-!cn,手动选择兜底国家
  - GEOSITE,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  # 本机进程兜底(本机中只有以下进程，保证不DNS泄露)
  - PROCESS-NAME,Proxifier.exe,手动选择兜底国家 # Proxifier
  - PROCESS-NAME,firefox.exe,手动选择兜底国家  # Firefox浏览器
  - PROCESS-NAME-REGEX,(?i)Chrome,手动选择兜底国家 # Chrome浏览器
  - PROCESS-NAME-REGEX,(?i)^(Safari|com\.apple\.WebKit),手动选择兜底国家 # MAC的Safari浏览器+莫名其妙的WebKit
  # 局域网客户端兜底(当局域网设备代理指向本机时，只有这样兜底，才能保证不DNS泄露)(这个最特殊，分流的是来源，其他Rules分流的是去向)
  - SRC-IP-CIDR,10.2.0.0/16,手动选择兜底国家
  - SRC-IP-CIDR,192.168.0.0/16,手动选择兜底国家
  # 最终兜底
  - MATCH,兜底组
